name: Save file from SECRET
on:
  push:
    branches:
      - "**"

jobs:
  save-file-from-secret:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Save the sercret file
        run: echo -n "${SECRET_FILE}" > secret_file.json
        env:
          SECRET_FILE: ${{ secrets.SECRET_FILE }}

      - name: Check
        run: |
          echo "-- sha256sum"
          sha256sum < secret_file.json
          echo "-- cat"
          cat secret_file.json
          echo "-- jq"
          jq .password secret_file.json
