name: Escaped field value
on:
  push:
    branches:
      - "**"

jobs:
  escaped-field-value:
    runs-on: ubuntu-latest
    environment: escape

    steps:
      - uses: actions/checkout@v2

      - name: Save the sercret file
        run: envsubst < secret_file_src_envsubst_esc.json  > secret_file.json
        env:
          NAME: ${{ secrets.NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Check
        run: |
          echo "-- sha256sum"
          jq < secret_file.json | sha256sum 
          echo "-- ファイル表示 cat secret_file.json"
          cat secret_file.json
          echo "-- フィールド表示 jq .password secret_file.json"
          jq .password secret_file.json
          echo "-- フィールド表示(RAW) jq -r .password secret_file.json"
          jq -r .password secret_file.json
