name: Biild file by variable-substitution
on:
  push:
    branches:
      - "**"

jobs:
  build-file-by-var-subst-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: mv secret_file_src.json secret_file.json

      - uses: microsoft/variable-substitution@v1 
        with:
          files: 'secret_file.json'
        env:
          name: ${{ secrets.NAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Check
        run: |
          echo "-- sha256sum"
          sha256sum < secret_file.json
          echo "-- ファイル表示 cat secret_file.json"
          cat secret_file.json
          echo "-- フィールド表示 jq .password secret_file.json"
          jq .password secret_file.json
