name: Upload files
on:
  release:
    types:
      - published

jobs:
  upload-files:
    runs-on: ubuntu-latest
    environment: upload

    steps:
      - uses: actions/checkout@v2

      - name: Save the sercret file
        run: |
          jq '.name = env.NAME' secret_file_src.json  \
          | jq '.password = env.PASSWORD' > secret_file.json
        env:
          NAME: ${{ secrets.NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Build
        run: zip secret_file_sourc.zip secret_file*.json

      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./secret_file_sourc.zip
          asset_name: secret_file_sourc.zip
          asset_content_type: application/zip
